import Head from "next/head";
import estilo from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={estilo.container_principal}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <p>React JS</p>
      </header>

      <main>
        <section className={estilo.secao_titulo}>
          <h1>React JS</h1>
          <p>Bilioteca JavaScript para criar SPAs</p>
          <a href='https://react.dev/' target="_blank">Site Oficial</a>
        </section>

        <section className={estilo.secao_requisitos}>
          <h3>Requisitos</h3>
          <p>Veja abaixo os requisitos minimos para aprender React JS</p>

          <div className={estilo.cards}>
            <div>
            <h3>HTML</h3>
            <p>Aprender a estruturar os elementos da página com HTML</p>
            </div>

            <div>
            <h3>CSS</h3>
            <p>Aprender a estilizar os elementos da página com CSS</p>
            </div>

            <div>
            <h3>JavaScript</h3>
            <p>Aprender a linguagem utilizada pelo React JS, o JavaScript</p>
            </div>
          </div>
        </section>
      </main>

      <footer>
        <p>Curso ded introdução de React.js</p>
      </footer>
    </div>
  );
}
